wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.6
    start_time: 1652331389
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      4: 3.8.6
      5: 0.12.16
      8:
      - 1
      - 2
      - 5
